#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-nnls
Version  : 1.6
Release  : 44
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/nnls_1.6.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/nnls_1.6.tar.gz
Summary  : The Lawson-Hanson Algorithm for Non-Negative Least Squares
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-nnls-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
algorithm for non-negative least squares (NNLS).  Also allows
        the combination of non-negative and non-positive constraints.

%package lib
Summary: lib components for the R-nnls package.
Group: Libraries

%description lib
lib components for the R-nnls package.


%prep
%setup -q -n nnls
pushd ..
cp -a nnls buildavx2
popd
pushd ..
cp -a nnls buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1731646982

%install
export SOURCE_DATE_EPOCH=1731646982
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/nnls/COPYRIGHTS
/usr/lib64/R/library/nnls/DESCRIPTION
/usr/lib64/R/library/nnls/INDEX
/usr/lib64/R/library/nnls/Meta/Rd.rds
/usr/lib64/R/library/nnls/Meta/features.rds
/usr/lib64/R/library/nnls/Meta/hsearch.rds
/usr/lib64/R/library/nnls/Meta/links.rds
/usr/lib64/R/library/nnls/Meta/nsInfo.rds
/usr/lib64/R/library/nnls/Meta/package.rds
/usr/lib64/R/library/nnls/NAMESPACE
/usr/lib64/R/library/nnls/NEWS
/usr/lib64/R/library/nnls/R/nnls
/usr/lib64/R/library/nnls/R/nnls.rdb
/usr/lib64/R/library/nnls/R/nnls.rdx
/usr/lib64/R/library/nnls/help/AnIndex
/usr/lib64/R/library/nnls/help/aliases.rds
/usr/lib64/R/library/nnls/help/nnls.rdb
/usr/lib64/R/library/nnls/help/nnls.rdx
/usr/lib64/R/library/nnls/help/paths.rds
/usr/lib64/R/library/nnls/html/00Index.html
/usr/lib64/R/library/nnls/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/nnls/libs/nnls.so
/V4/usr/lib64/R/library/nnls/libs/nnls.so
/usr/lib64/R/library/nnls/libs/nnls.so
